puts 'Seeding people'
Person.create(name: 'David Yurek')
Person.create(name: 'Dave Hempy')
Person.create(name: 'Chase Southard')
Person.create(name: 'Chase James')
Person.create(name: 'Todd Wiley')
Person.create(name: 'Sarah Vessels')
Person.create(name: 'Nick Warner')
Person.create(name: 'Lindsay Rall')
Person.create(name: 'Summer Smith')
Person.create(name: 'Michael Bates')
Person.create(name: 'Michael Huelsman')
Person.create(name: 'Graham Hough')
Person.create(name: 'Tristan Basil')
Person.create(name: 'Erik Mudrak')
puts 'Seeding calendar'
Calendar.create(date: Date.today, current_day_id: 1, person_order: [*1..Person.all.count])
